// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaos/serverexprimentation/v1/serverexperimentation.proto

package serverexperimentationv1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/lyft/clutch/backend/api/api/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerTestSpecification struct {
	// Types that are valid to be assigned to Config:
	//	*ServerTestSpecification_Abort
	//	*ServerTestSpecification_Latency
	Config               isServerTestSpecification_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ServerTestSpecification) Reset()         { *m = ServerTestSpecification{} }
func (m *ServerTestSpecification) String() string { return proto.CompactTextString(m) }
func (*ServerTestSpecification) ProtoMessage()    {}
func (*ServerTestSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbfb380d1e693e08, []int{0}
}

func (m *ServerTestSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTestSpecification.Unmarshal(m, b)
}
func (m *ServerTestSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTestSpecification.Marshal(b, m, deterministic)
}
func (m *ServerTestSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTestSpecification.Merge(m, src)
}
func (m *ServerTestSpecification) XXX_Size() int {
	return xxx_messageInfo_ServerTestSpecification.Size(m)
}
func (m *ServerTestSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTestSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTestSpecification proto.InternalMessageInfo

type isServerTestSpecification_Config interface {
	isServerTestSpecification_Config()
}

type ServerTestSpecification_Abort struct {
	Abort *AbortFault `protobuf:"bytes,2,opt,name=abort,proto3,oneof"`
}

type ServerTestSpecification_Latency struct {
	Latency *LatencyFault `protobuf:"bytes,3,opt,name=latency,proto3,oneof"`
}

func (*ServerTestSpecification_Abort) isServerTestSpecification_Config() {}

func (*ServerTestSpecification_Latency) isServerTestSpecification_Config() {}

func (m *ServerTestSpecification) GetConfig() isServerTestSpecification_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ServerTestSpecification) GetAbort() *AbortFault {
	if x, ok := m.GetConfig().(*ServerTestSpecification_Abort); ok {
		return x.Abort
	}
	return nil
}

func (m *ServerTestSpecification) GetLatency() *LatencyFault {
	if x, ok := m.GetConfig().(*ServerTestSpecification_Latency); ok {
		return x.Latency
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerTestSpecification) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerTestSpecification_Abort)(nil),
		(*ServerTestSpecification_Latency)(nil),
	}
}

// Targets requests from downstream_cluster -> upstream_cluster
type ClusterPairTarget struct {
	// The name of the downstream cluster
	DownstreamCluster string `protobuf:"bytes,1,opt,name=downstream_cluster,json=downstreamCluster,proto3" json:"downstream_cluster,omitempty"`
	// The name of the upstream cluster
	UpstreamCluster      string   `protobuf:"bytes,2,opt,name=upstream_cluster,json=upstreamCluster,proto3" json:"upstream_cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterPairTarget) Reset()         { *m = ClusterPairTarget{} }
func (m *ClusterPairTarget) String() string { return proto.CompactTextString(m) }
func (*ClusterPairTarget) ProtoMessage()    {}
func (*ClusterPairTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbfb380d1e693e08, []int{1}
}

func (m *ClusterPairTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterPairTarget.Unmarshal(m, b)
}
func (m *ClusterPairTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterPairTarget.Marshal(b, m, deterministic)
}
func (m *ClusterPairTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterPairTarget.Merge(m, src)
}
func (m *ClusterPairTarget) XXX_Size() int {
	return xxx_messageInfo_ClusterPairTarget.Size(m)
}
func (m *ClusterPairTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterPairTarget.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterPairTarget proto.InternalMessageInfo

func (m *ClusterPairTarget) GetDownstreamCluster() string {
	if m != nil {
		return m.DownstreamCluster
	}
	return ""
}

func (m *ClusterPairTarget) GetUpstreamCluster() string {
	if m != nil {
		return m.UpstreamCluster
	}
	return ""
}

type AbortFault struct {
	// Types that are valid to be assigned to Target:
	//	*AbortFault_ClusterPair
	Target isAbortFault_Target `protobuf_oneof:"target"`
	// The percentage of requests that will be faulted.
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// The abort HTTP status that will be returned.
	HttpStatus           int32    `protobuf:"varint,3,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbortFault) Reset()         { *m = AbortFault{} }
func (m *AbortFault) String() string { return proto.CompactTextString(m) }
func (*AbortFault) ProtoMessage()    {}
func (*AbortFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbfb380d1e693e08, []int{2}
}

func (m *AbortFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbortFault.Unmarshal(m, b)
}
func (m *AbortFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbortFault.Marshal(b, m, deterministic)
}
func (m *AbortFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbortFault.Merge(m, src)
}
func (m *AbortFault) XXX_Size() int {
	return xxx_messageInfo_AbortFault.Size(m)
}
func (m *AbortFault) XXX_DiscardUnknown() {
	xxx_messageInfo_AbortFault.DiscardUnknown(m)
}

var xxx_messageInfo_AbortFault proto.InternalMessageInfo

type isAbortFault_Target interface {
	isAbortFault_Target()
}

type AbortFault_ClusterPair struct {
	ClusterPair *ClusterPairTarget `protobuf:"bytes,1,opt,name=cluster_pair,json=clusterPair,proto3,oneof"`
}

func (*AbortFault_ClusterPair) isAbortFault_Target() {}

func (m *AbortFault) GetTarget() isAbortFault_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AbortFault) GetClusterPair() *ClusterPairTarget {
	if x, ok := m.GetTarget().(*AbortFault_ClusterPair); ok {
		return x.ClusterPair
	}
	return nil
}

func (m *AbortFault) GetPercent() float32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *AbortFault) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AbortFault) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AbortFault_ClusterPair)(nil),
	}
}

type LatencyFault struct {
	// Types that are valid to be assigned to Target:
	//	*LatencyFault_ClusterPair
	Target isLatencyFault_Target `protobuf_oneof:"target"`
	// The percentage of requests that will be slowed down.
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// The latency duration in milliseconds.
	DurationMs           int32    `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatencyFault) Reset()         { *m = LatencyFault{} }
func (m *LatencyFault) String() string { return proto.CompactTextString(m) }
func (*LatencyFault) ProtoMessage()    {}
func (*LatencyFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbfb380d1e693e08, []int{3}
}

func (m *LatencyFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatencyFault.Unmarshal(m, b)
}
func (m *LatencyFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatencyFault.Marshal(b, m, deterministic)
}
func (m *LatencyFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatencyFault.Merge(m, src)
}
func (m *LatencyFault) XXX_Size() int {
	return xxx_messageInfo_LatencyFault.Size(m)
}
func (m *LatencyFault) XXX_DiscardUnknown() {
	xxx_messageInfo_LatencyFault.DiscardUnknown(m)
}

var xxx_messageInfo_LatencyFault proto.InternalMessageInfo

type isLatencyFault_Target interface {
	isLatencyFault_Target()
}

type LatencyFault_ClusterPair struct {
	ClusterPair *ClusterPairTarget `protobuf:"bytes,1,opt,name=cluster_pair,json=clusterPair,proto3,oneof"`
}

func (*LatencyFault_ClusterPair) isLatencyFault_Target() {}

func (m *LatencyFault) GetTarget() isLatencyFault_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *LatencyFault) GetClusterPair() *ClusterPairTarget {
	if x, ok := m.GetTarget().(*LatencyFault_ClusterPair); ok {
		return x.ClusterPair
	}
	return nil
}

func (m *LatencyFault) GetPercent() float32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *LatencyFault) GetDurationMs() int32 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LatencyFault) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LatencyFault_ClusterPair)(nil),
	}
}

func init() {
	proto.RegisterType((*ServerTestSpecification)(nil), "clutch.chaos.serverexperimentation.v1.ServerTestSpecification")
	proto.RegisterType((*ClusterPairTarget)(nil), "clutch.chaos.serverexperimentation.v1.ClusterPairTarget")
	proto.RegisterType((*AbortFault)(nil), "clutch.chaos.serverexperimentation.v1.AbortFault")
	proto.RegisterType((*LatencyFault)(nil), "clutch.chaos.serverexperimentation.v1.LatencyFault")
}

func init() {
	proto.RegisterFile("chaos/serverexprimentation/v1/serverexperimentation.proto", fileDescriptor_bbfb380d1e693e08)
}

var fileDescriptor_bbfb380d1e693e08 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x93, 0xb8, 0xdd, 0xea, 0x4b, 0x61, 0x77, 0xe7, 0xd2, 0x6e, 0x51, 0x08, 0x85, 0x85,
	0x8a, 0x90, 0x90, 0x2e, 0x88, 0x1e, 0x1d, 0x41, 0x56, 0x50, 0x94, 0x74, 0x4f, 0x82, 0x94, 0xe9,
	0x74, 0xda, 0x0e, 0xa4, 0x33, 0x61, 0xf2, 0x12, 0xdd, 0x93, 0x7f, 0x9a, 0x57, 0x0f, 0x7a, 0xf7,
	0x6f, 0xe9, 0x49, 0x32, 0x49, 0x68, 0x75, 0x7b, 0xe8, 0xd1, 0x5b, 0x32, 0xdf, 0xfb, 0x7e, 0xf3,
	0xbe, 0xf7, 0x18, 0x78, 0xc9, 0xd7, 0x4c, 0xe7, 0x51, 0x2e, 0x4c, 0x29, 0x8c, 0xf8, 0x9a, 0x19,
	0xb9, 0x11, 0x0a, 0x19, 0x4a, 0xad, 0xa2, 0x32, 0xde, 0x9d, 0x8b, 0x3d, 0x21, 0xcc, 0x8c, 0x46,
	0x4d, 0xae, 0x78, 0x5a, 0x20, 0x5f, 0x87, 0x96, 0x10, 0x1e, 0xae, 0x2c, 0xe3, 0xe1, 0xe3, 0x95,
	0xd6, 0xab, 0x54, 0x44, 0x2c, 0x93, 0x11, 0x53, 0x4a, 0xd7, 0x4a, 0x5e, 0x43, 0x86, 0xfd, 0x92,
	0xa5, 0x72, 0xc1, 0x50, 0x44, 0xed, 0x47, 0x23, 0x5c, 0x36, 0x36, 0xfb, 0x37, 0x2f, 0x96, 0x11,
	0x53, 0x77, 0x8d, 0x34, 0xa8, 0x50, 0x65, 0x7c, 0x9f, 0x36, 0xfa, 0xee, 0x42, 0x7f, 0x6a, 0x1b,
	0xb9, 0x15, 0x39, 0x4e, 0x33, 0xc1, 0xe5, 0x52, 0x72, 0x5b, 0x42, 0xde, 0x42, 0x87, 0xcd, 0xb5,
	0xc1, 0x81, 0x17, 0xb8, 0x63, 0x7f, 0x12, 0x87, 0x47, 0xb5, 0x1f, 0xbe, 0xaa, 0x3c, 0x6f, 0x58,
	0x91, 0xe2, 0x8d, 0x93, 0xd4, 0x04, 0xf2, 0x01, 0xba, 0x29, 0x43, 0xa1, 0xf8, 0xdd, 0xe0, 0x81,
	0x85, 0x5d, 0x1f, 0x09, 0x7b, 0x57, 0xbb, 0x5a, 0x5c, 0x4b, 0xa1, 0x0f, 0xe1, 0x94, 0x6b, 0xb5,
	0x94, 0xab, 0xd1, 0x37, 0xb8, 0x78, 0x9d, 0x16, 0x39, 0x0a, 0xf3, 0x91, 0x49, 0x73, 0xcb, 0xcc,
	0x4a, 0x20, 0x79, 0x0e, 0x64, 0xa1, 0xbf, 0xa8, 0x1c, 0x8d, 0x60, 0x9b, 0x19, 0xaf, 0xf5, 0x81,
	0x1b, 0xb8, 0xe3, 0x47, 0xb4, 0xbb, 0xa5, 0x27, 0xc6, 0x0b, 0xdc, 0xe4, 0x62, 0x57, 0xd2, 0x10,
	0xc8, 0x04, 0xce, 0x8b, 0xec, 0x1f, 0x97, 0xf7, 0xb7, 0xeb, 0xac, 0x2d, 0x68, 0x3c, 0xa3, 0x5f,
	0x2e, 0xc0, 0x2e, 0x33, 0xf9, 0x0c, 0xbd, 0xc6, 0x39, 0xcb, 0x98, 0xac, 0x2f, 0xf5, 0x27, 0x2f,
	0x8e, 0xcc, 0x7b, 0x2f, 0xca, 0x8d, 0x93, 0xf8, 0x7c, 0x77, 0x48, 0x9e, 0x42, 0x37, 0x13, 0x86,
	0x0b, 0x55, 0xaf, 0xc5, 0xa3, 0x67, 0x5b, 0xda, 0x03, 0x78, 0xe2, 0x38, 0x3f, 0xe8, 0x95, 0xe3,
	0x38, 0x4e, 0xd2, 0xea, 0xe4, 0x19, 0xf8, 0x6b, 0xc4, 0x6c, 0x96, 0x23, 0xc3, 0x22, 0xb7, 0x83,
	0xef, 0x50, 0xd8, 0xd2, 0xee, 0xb0, 0x73, 0xfe, 0xfb, 0x24, 0xe0, 0x09, 0x54, 0xf2, 0xd4, 0xaa,
	0xd5, 0x40, 0xd1, 0x5e, 0x38, 0xfa, 0xe9, 0x42, 0x6f, 0x7f, 0xec, 0xff, 0x51, 0xa2, 0x31, 0xf8,
	0x8b, 0xc2, 0x58, 0xf4, 0x6c, 0xd3, 0x26, 0xaa, 0x36, 0x33, 0xf4, 0x02, 0x27, 0x81, 0x56, 0x7b,
	0xbf, 0x17, 0x87, 0x5e, 0x7e, 0xea, 0x1f, 0xec, 0xad, 0x8c, 0xe7, 0xa7, 0xf6, 0x0d, 0x5c, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xee, 0x59, 0x67, 0x6c, 0xd3, 0x03, 0x00, 0x00,
}
